prevent division of untyped ints always yielding zero
gonum/gonum pull request #1653
Opened 2021-06-05 17:29 UTC by soypat

Please take a look at the line I changed. The following operation:
```go
scale = 1 / 8 / maxbtmp
```
always yields zero. I added decimal points to `1` and `8` to fix this undesired behavior.

2021-06-05 22:00 UTC, kortschak requested changes
This branch is not tested, so it would be nice if we could get an input that exercises this case.

2021-06-06 15:27 UTC, vladimir-ch commented on lapack/gonum/dlasy2.go
> +		scale = 1. / 8. / maxbtmp
Yes, it can be that `8 * maxbtmp` overflows and `scale` is then 0 but with `(1.0 / 8.0) / maxbtmp` the scale is non-zero (even though tiny).

2021-06-09 23:12 UTC, soypat commented
Should I close this request and let someone experienced with the function test this? I've tried giving input that's large enough to trigger the condition but it results in errors all over the place. I'm unfamiliar with what it is that is being tested. Here's what I tried:
```go
    // declare tl, tr, b etc. in dlasy2.go in testlapack
     for i := range tl.Data {
		tl.Data[i] = math.Abs(tl.Data[i]) * 1e-10
	}
	if len(b.Data) > 0 {
		b.Data[0] = 1e64
      }
```

2021-06-11 10:06 UTC, vladimir-ch commented
> Should I close this request and let someone experienced with the function test this?

No, you found the bug and the fix is clear even without having it covered by a test. After you've added yourself to CONTRIBUTORS/AUTHORS, I'll merge this PR and then try to take a look at the test.

2021-06-11 13:27 UTC, vladimir-ch approved these changes

2021-06-11 21:37 UTC, kortschak approved these changes

2021-06-11 22:16 UTC, merged