integrate: use more efficient "is sorted" routine
gonum/gonum pull request #1950
Opened 2024-03-06 21:01 UTC by jbduncan

This PR introduces a modernization change that is not necessarily related to #617 but which was spun out from my attempts at generifying the leaves of `graph`. Benchmarks to follow.

Blocked by https://github.com/gonum/gonum/pull/1940.

2024-03-06 23:04 UTC, jbduncan commented
Funnily enough, there are no benchmarks that exercise `integrate.(Simpsons|Trapezoidal)` directly or indirectly, so there's nothing to run here.

2024-03-08 10:33 UTC, sbinet submitted a review, later dismissed
LGTM.

2024-03-08 10:46 UTC, kortschak requested changes
Please provide relevant benchmark analysis.

2024-03-08 10:46 UTC, kortschak commented on .github/workflows/staticcheck.yml
> +          cache-key: ${{ matrix.go }}
Final new line.

2024-03-08 19:08 UTC, jbduncan commented on .github/workflows/staticcheck.yml
> +          cache-key: ${{ matrix.go }}
Fixed in PR #1940.

2024-03-08 19:10 UTC, jbduncan commented
@kortschak Oh, [I've just seen](https://github.com/gonum/gonum/pull/1950#pullrequestreview-1924597291) your request to provide benchmarks anyway, sorry for not seeing it sooner!

So I'll run benchmarks for this PR and all the others one after another (apart from #1940, as all it affects is GitHub Actions). Any objections to this plan? :)

2024-03-09 02:03 UTC, kortschak commented
> So I'll run benchmarks for this PR and all the others one after another (apart from https://github.com/gonum/gonum/pull/1940, as all it affects is GitHub Actions). Any objections to this plan? :)

That's fine with me.

2024-03-11 12:28 UTC, jbduncan commented
As discussed in https://github.com/gonum/gonum/pull/1956#issuecomment-1988326786, I'll make some new benchmarks as soon as I can.

2024-03-15 21:11 UTC, kortschak commented
This needs to pick up the changes in master.

2024-03-16 13:47 UTC, jbduncan commented
> This needs to pick up the changes in master.

Done.

2024-03-23 00:43 UTC, kortschak reviewed
Needs evidence for efficiency improvement.

2024-04-07 16:30 UTC, jbduncan commented
On re-reading the source code, I see that `sort.Float64sAreSorted` delegates to `slices.IsSorted`, so I'm not convinced there'd be any perf improvements and so I'm closing this PR.

2024-04-07 16:30 UTC, closed without merging